src/Werte/Bedarf/Thema/Bedarfsthema.php
src/Werte/Bedarf/Thema/Themen/Altersvorsorge.php
src/Werte/Bedarf/Thema/Themen/Berufsunfaehigkeit.php
src/Werte/Bedarf/Thema/Themen/KVZStationaer.php
src/Werte/Bedarf/Thema/Themen/Kfz.php
src/Werte/Bedarf/Thema/Themen/Krankentagegeld.php
src/Werte/Bedarf/Thema/Themen/Pflegevorsorge.php
src/Werte/Bedarf/Thema/Themen/PrivateKrankenversicherung.php
src/Werte/Bedarf/Thema/Themen/Privathaftpflicht.php
src/Werte/Bedarf/Thema/Themen/Risikoleben.php
src/Werte/Bedarf/Thema/Themen/Unfallversicherung.php
src/Werte/Bedarf/Thema/Themen/Zahnzusatz.php

Themennamen anpassen #116

---

composer.json
src/Werte/Bedarf/Thema/Bedarfsthemen.php
src/Werte/Bedarf/Thema/Themen/AmbulanteKrankenzusatzversicherung.php
tests/Werte/Bedarf/Thema/BedarfsthemenTest.php

Add ambulante krankenzusatzversicherung

---

.travis.yml
src/Werte/Person/Raucherstatus/Raucherstatus.php
src/Werte/Person/Raucherstatus/Raucherstatus/Gelegentlich.php
src/Werte/Person/Raucherstatus/Raucherstatus/Ja.php
src/Werte/Person/Raucherstatus/Raucherstatus/Nein.php
src/Werte/Person/Raucherstatus/Raucherstatus/Unbekannt.php
src/Werte/Person/Raucherstatus/RaucherstatusInterface.php
tests/Werte/Person/Raucherstatus/RaucherstatusTest.php

[Raucherstatus] unterhalb von Person anlegen #128

---

src/Werte/Person/Bildungsabschluss/Bildung/Beruflich/AbschlussAlsMeister.php
src/Werte/Person/Bildungsabschluss/Bildung/Beruflich/AusbildungHandwerk.php
src/Werte/Person/Bildungsabschluss/Bildung/Beruflich/AusbildungKaufmaennisch.php
src/Werte/Person/Bildungsabschluss/Bildung/Beruflich/AusbildungMitWeiterbildung.php
src/Werte/Person/Bildungsabschluss/Bildung/Beruflich/Auszubildender.php
src/Werte/Person/Bildungsabschluss/Bildung/Beruflich/BetriebswirtFachwirt.php
src/Werte/Person/Bildungsabschluss/Bildung/Hochschule/BachelorFachhochschule.php
src/Werte/Person/Bildungsabschluss/Bildung/Hochschule/BachelorUniversitaet.php
src/Werte/Person/Bildungsabschluss/Bildung/Hochschule/DiplomFachhochschule.php
src/Werte/Person/Bildungsabschluss/Bildung/Hochschule/DiplomMagister.php
src/Werte/Person/Bildungsabschluss/Bildung/Hochschule/ImStudium.php
src/Werte/Person/Bildungsabschluss/Bildung/Hochschule/MasterFachhochschule.php
src/Werte/Person/Bildungsabschluss/Bildung/Hochschule/MasterUniversitaet.php
src/Werte/Person/Bildungsabschluss/Bildung/Hochschule/Promotion.php
src/Werte/Person/Bildungsabschluss/Bildung/Hochschule/Staatsexamen.php
src/Werte/Person/Bildungsabschluss/Bildung/Schule/Abitur.php
src/Werte/Person/Bildungsabschluss/Bildung/Schule/Fachabitur.php
src/Werte/Person/Bildungsabschluss/Bildung/Schule/Hauptschulabschluss.php
src/Werte/Person/Bildungsabschluss/Bildung/Schule/KeinAbschluss.php
src/Werte/Person/Bildungsabschluss/Bildung/Schule/MittlereReife.php
src/Werte/Person/Bildungsabschluss/Bildungsabschluss.php
src/Werte/Person/Bildungsabschluss/BildungsabschlussInterface.php
src/Werte/Person/Bildungsabschluss/Bildungsgruppen.php
tests/Werte/Person/Bildungsabschluss/BildungsabschlussTest.php

höchster Bildungsabschluß #131

---

src/Werte/Sparte/Sparten/PrivateSachversicherung.php

VER-437 #close : Werte Repo für Hunde- und Pferdehaftpflicht ergänzen
https://demvsystems.atlassian.net/browse/VER-437

add Hunde- & Pferdehaftpflich

---

src/Werte/Sparte/Sparten/Krankenversicherung.php
src/Werte/Sparte/Sparten/PrivateSachversicherung.php

Added Sparten-Ids: Krankenversicherung & Elektronikversicherung

---

src/Werte/Person/Beziehung/Beziehungstypen.php
src/Werte/Person/Beziehung/GegenbeziehungFactory.php
src/Werte/Person/Beziehung/Privat/Mitbewohner.php
tests/Werte/Person/Beziehung/BeziehungstypenTest.php
tests/Werte/Person/Beziehung/GegenbeziehungTest.php

[TDKW-117]
[TDKW-117]: https://demvsystems.atlassian.net/browse/TDKW-117

add mitbewohner beziehung

---

src/Werte/Person/Beziehung/Beruflich/Berufsbetreuer.php
src/Werte/Person/Beziehung/Beruflich/Betreuter.php

https://demvsystems.atlassian.net/browse/VER-1265

VER-1265 Neuer Beziehungsverhältnis Typ

---

src/Werte/Bedarf/Thema/Bedarfsthemen.php
src/Werte/Bedarf/Thema/Themen/Funktionsinvaliditaet.php
tests/Werte/Bedarf/Thema/BedarfsthemenTest.php

Wenn ich das richtig gesehen hab, fehlt der hier noch @alexmpunkt?
adds Funktionsinvaliditaet Bedarfsthema

[AB-1533] Bedarfsthema Funktionsinvaliditaet aka Multi-Risk

---

src/Werte/Dokumente/Dokumenttypen/Produktinformationsblatt.php

[VER-2006]
[VER-2006]: https://demvsystems.atlassian.net/browse/VER-2006

VER-2006 Dokumente korrekt in PW hochladen

---

src/Werte/Dokumente/Dokumenttypen.php
tests/Werte/DokumenttypenTest.php

[VER-2231]
[VER-2231]: https://demvsystems.atlassian.net/browse/VER-2231

VER-2231 : Prüfung der PDF's in KV (keine PDFs von GC)

---

src/Werte/Dokumente/Dokumenttypen/Zertifikat.php

add new document type

---

.github/workflows/backend.yml
composer.json
src/Werte/Beitragsbemessung/BBG.php

[FM-130]
[FM-130]: https://demvsystems.atlassian.net/browse/FM-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MERGE AM 31.12] fix(bbg): set betrag to value for 2022

---

src/Werte/Bedarf/Thema/Themen/Berufshaftpflicht.php
src/Werte/Bedarf/Thema/Themen/Betriebshaftpflicht.php
src/Werte/Bedarf/Thema/Themen/Cyberversicherung.php
src/Werte/Bedarf/Thema/Themen/D_O.php
src/Werte/Bedarf/Thema/Themen/Firmenrechtsschutz.php
src/Werte/Bedarf/Thema/Themen/Geschaeftsinhaltsversicherung.php
src/Werte/Bedarf/Thema/Themen/GewerblicheGebaeudeversicherung.php
src/Werte/Bedarf/Thema/Themen/Vermoegensschadenhaftpflicht.php

[FM-75]
[FM-4]
[FM-75]: https://demvsystems.atlassian.net/browse/FM-75?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FM-4]: https://demvsystems.atlassian.net/browse/FM-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FM-75] & [FM-4] Bedarfsthemen für Gewerbliche Absicherungen

---

src/Werte/Bedarf/Thema/Bedarfsthemen.php
tests/Werte/Bedarf/Thema/BedarfsthemenTest.php

[FM-75]
[FM-4]
[FM-75]: https://demvsystems.atlassian.net/browse/FM-75?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FM-4]: https://demvsystems.atlassian.net/browse/FM-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FM-75] & [FM-4] add new business topics to Bedarfsthemen

---

src/Werte/Bedarf/Thema/Bedarfsthemen.php
src/Werte/Bedarf/Thema/Themen/Diensthaftpflicht.php
src/Werte/Bedarf/Thema/Themen/Dienstunfaehigkeitsversicherung.php
src/Werte/Sparte/Sparten/Privathaftpflicht.php
src/Werte/Sparte/Sparten/Vorsorge.php
tests/Werte/Bedarf/Thema/BedarfsthemenTest.php

[FM-154] 
[FM-154]: https://demvsystems.atlassian.net/browse/FM-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FM-154] Bedarf nach Taetigkeit/Sparten

---

src/Werte/Bedarf/Thema/Bedarfsthemen.php
tests/Werte/Bedarf/Thema/BedarfsthemenTest.php

[FM-154] 
[FM-154]: https://demvsystems.atlassian.net/browse/FM-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FM-154] feat: return bedarfsthemen when taetigkeit is null

---

src/Werte/Bedarf/Thema/Themen/Dienstunfaehigkeitsversicherung.php

[FM-276]
[FM-276]: https://demvsystems.atlassian.net/browse/FM-276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FM-276] fix(du): typo in display name

---

src/Werte/Beitragsbemessung/BBG.php

[FM-478]
Zum 02.02.2023 veröffentlichen
[FM-478]: https://demvsystems.atlassian.net/browse/FM-478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FM-478] Anpassen der Bemessungsgrenzen im Bedarf

---

src/Werte/Dokumente/Dokumenttypen.php
src/Werte/Dokumente/Dokumenttypen/Evb.php
tests/Werte/DokumenttypenTest.php

[VER-3748]
Gehört zu https://github.com/demvsystems/vergleichsrechner/pull/4575
[VER-3748]: https://demvsystems.atlassian.net/browse/VER-3748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: added eVB to Dokumenttypen.php

---

src/Werte/Sparte/Sparten/PrivateSachversicherung.php

add some KFZ SpartenIds
[KA-162]
[KA-156]
[KA-162]: https://demvsystems.atlassian.net/browse/KA-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KA-156]: https://demvsystems.atlassian.net/browse/KA-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KA-162-Bedarf-KFZ

---

src/Werte/Person/Beziehung/Beruflich/Arzt.php
src/Werte/Person/Beziehung/Beruflich/BautraegerKaeufer.php
src/Werte/Person/Beziehung/Beruflich/ImmobilienMakler.php
src/Werte/Person/Beziehung/Beruflich/Notar.php
src/Werte/Person/Beziehung/Beruflich/NotarMandant.php
src/Werte/Person/Beziehung/Beruflich/Patient.php
src/Werte/Person/Beziehung/Beruflich/Steuerberater.php
src/Werte/Person/Beziehung/Beruflich/SteuerberaterMandant.php
src/Werte/Person/Beziehung/Beziehungstypen.php
src/Werte/Person/Beziehung/GegenbeziehungFactory.php
tests/Werte/Person/Beziehung/BeziehungstypenTest.php
tests/Werte/Person/Beziehung/GegenbeziehungTest.php

[BIP-2642] Anpassungen im Werte Repo
[BIP-2642]: https://demvsystems.atlassian.net/browse/BIP-2642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BIP-2642: add new client relations

---

src/Werte/Person/Bildungsabschluss/Bildung/Beruflich/AusbildungSonstige.php
src/Werte/Person/Bildungsabschluss/Bildungsabschluss.php
tests/Werte/Person/Bildungsabschluss/BildungsabschlussTest.php

[VER-4159]
[VER-4159]: https://demvsystems.atlassian.net/browse/VER-4159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VER-4159 - Added AusbildungSonstige.php

---

src/Werte/Person/Taetigkeitsstatus/Status/Bundeswehr.php
src/Werte/Person/Taetigkeitsstatus/Taetigkeitsstatus.php
tests/Werte/Person/Taetigkeitsstatus/TaetigkeitsstatusTest.php

https://demvsystems.atlassian.net/browse/VER-4045

Neuer Wert Berufsstatus

---

src/Werte/Sparte/Sparten/Gewerbe.php
src/Werte/Sparte/Sparten/PrivateSachversicherung.php

[VER-4366]
[VER-4366]: https://demvsystems.atlassian.net/browse/VER-4366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VER-4366: neue KFZ-Sparten Release vorbereiten

---

src/Werte/Sparte/Sparten/Krankenversicherung.php

[KA-375]
[KA-375]: https://demvsystems.atlassian.net/browse/KA-375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KA-375 - Private Krankenzusatzversicherung

---

src/Werte/Sparte/Sparten/Krankenversicherung.php

[KA-375] Der Wert ist schon an anderer Stelle versteckt gewesen.
[KA-375]: https://demvsystems.atlassian.net/browse/KA-375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KA-375 - revert private Krankenzusatzversicherung

---

src/Werte/Sparte/Sparten/Gewerbe.php

[VER-5052]
[VER-5052]: https://demvsystems.atlassian.net/browse/VER-5052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

task(VER-5052): adjusted product combo id to match the one in pw

---

src/Werte/Sparte/Sparten/Vorsorge.php

[KA-825]
[KA-825]: https://demvsystems.atlassian.net/browse/KA-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[KA-825] feat(Vorsorge): add further bav sparten

---

src/Werte/Sparte/Sparten/Vorsorge.php

[KA-825]
[KA-825]: https://demvsystems.atlassian.net/browse/KA-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[KA-825] fix(Vorsorge): add missing bav suffix

---

src/Werte/Dokumente/Dokumenttypen.php
src/Werte/Dokumente/Dokumenttypen/Schweigepflichtentbindung.php
tests/Werte/DokumenttypenTest.php

[VER-5171]
[VER-5171]: https://demvsystems.atlassian.net/browse/VER-5171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

task(VER-5171): added schweigepflichtenbindung document

---

src/Werte/Bedarf/Thema/Themen/Tierhalterhaftpflicht.php

adds hunde und pferdehaftpflicht to tierhalter bedarfsthema

feat: update tierhalter bedarf thema
